## **a_tensor_initialization**

In [1]:
import torch
import numpy as np

In [2]:
# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device='cpu') # [1, 2, 3]를 사용해서 새로운 텐서 생성
print(t1.dtype) # torch.Tensor()는 기본적으로 float32 타입 사용
print(t1.device) # 텐서가 cpu에 할당
print(t1.requires_grad) # 그라디언트 추적을 하지 X
print(t1.size()) # 텐서의 크기
print(t1.shape) # 텐서의 크기

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [3]:
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)
print(t2.device)
print(t2.requires_grad)
print(t2.size())
print(t2.shape)

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [4]:
a1 = torch.tensor(1) # 0차원
print(a1.shape, a1.ndim)

a2 = torch.tensor([1]) # 1차원
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5]) # 1차원
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]]) # 2차원
print(a4.shape, a4.ndim)

a5 = torch.tensor([ # 2차원
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([ # 3차원
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3


In [5]:
a7 = torch.tensor([ # 4차원
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

a8 = torch.tensor([ # 4차원
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)


a9 = torch.tensor([ # 5차원
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

a10 = torch.tensor([ # 2차원
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a10 = torch.tensor([ # 3차원
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

'''
a11 = torch.tensor([ # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])
'''
# 추가 코드
# 차원의 크기가 맞아야 함
a11 = torch.tensor([ # 4차원
    [[[1, 2, 3], [4, 5, 6]]],
    [[[1, 2, 3], [4, 5, 6]]],
    [[[1, 2, 3], [4, 5, 6]]],
    [[[1, 2, 3], [4, 5, 6]]],
])

torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


---
**🔎기술적 사항/고찰 내용**

**torch.Tensor()**

 - 기본적으로 float32 타입으로 텐서를 생성한다.
 
**torch.tensor()**

 - 입력된 값의 데이터 타입으로 텐서를 생성한다.
 - ex. [1, 2, 3]는 int64 타입

**Rank**

 - 0차원 텐서: 스칼라
 - 1차원 텐서 (행, 열): 벡터
 - 2차원 텐서 (배치, 높이, 너비): 행렬
 - 3차원 이상의 텐서: 다차원 배열, 이미지 데이터 같은 복잡한 구조에 활용됨

<br/><br/> 
## **b_tensor_initialization_copy**

In [6]:
# 리스트를 텐서로 변환
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

# 리스트의 요소를 바꾼다면?
l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1) # 바뀌지 않은 값 출력
print(t2) # 바뀌지 않은 값 출력
print(t3) # 바뀐 값 출력

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [7]:
# Numpy 배열을 텐서로 변환
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

# 배열의 요소를 바꾼다면?
l4[0] = 100 
l5[0] = 100
l6[0] = 100

print(t4) # 바뀌지 않은 값 출력
print(t5) # 바뀌지 않은 값 출력
print(t6) # 바뀐 값 출력

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)


---
**🔎기술적 사항/고찰 내용**

**torch.Tensor()**
- 데이터를 복사하여 텐서를 만든다.
- float32 dtype (기본값)

**torch.tensor()**
- 데이터를 복사하여 텐서를 만든다.
- 리스트/배열의 dtype을 따른다.

**torch.as_tensor()**
- 데이터를 복사하지 않고 메모리를 공유한다.
- 리스트/배열이 수정되면 텐서도 바뀐다.

<br/><br/>
## **c_tensor_initialization_constant_values**

In [8]:
t1 = torch.ones(size=(5,))  # 크기가 (5,)인 1로 채워진 1차원 텐서 생성
t1_like = torch.ones_like(input=t1) # t1과 같은 모양에 1로 채워진 텐서 생성
print(t1)
print(t1_like)

t2 = torch.zeros(size=(6,))
t2_like = torch.zeros_like(input=t2)
print(t2)
print(t2_like)

t3 = torch.empty(size=(4,))  # 크기가 (4,)인 비어있는 텐서 생성
t3_like = torch.empty_like(input=t3) # t3과 같은 모양의 비어있는 텐서 생성
print(t3)
print(t3_like)

t4 = torch.eye(n=3) # 3x3 크기의 단위행렬 생성
print(t4)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0.0000, 1.8750, 0.0000, 0.0000])
tensor([-8.3304e-17,  1.7937e-42,  0.0000e+00,  0.0000e+00])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


---
**🔎기술적 사항/고찰 내용**

t1 = torch.ones(5)
- 크기가 5인 '1'로 채워진 텐서를 생성한다.

torch.ones_like(input=t1)
- t1와 같은 모양의 '1'로 채워진 텐서를 생성한다.
- torch.zeros(n) / torch.zeros_like(input=t1)
- torch.empty(n) / torch.empty_like(input=t1)

torch.eye(n=3)
- 3x3 크기의 단위행렬을 생성한다.

<br/><br/>
## **d_tensor_initialization_random_values**

In [9]:
# 10이상 20미만의 정수값으로 채워진 1x2 크기의 텐서 생성
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

# 0과 1 사이의 값으로 채워진 1x3 크기의 텐서 생성
t2 = torch.rand(size=(1, 3))
print(t2)

# 평균이 0이고, 표준편차가 1인 정규분포에서 추출된 1x3 크기의 텐서 생성
t3 = torch.randn(size=(1, 3))
print(t3)

# 평균이 10, 표준편차가 1인 정규분포에서 추출된 3x2 크기의 텐서 생성
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

# 0부터 5까지 모든 데이터를 균등하게 나눈 텐서 생성
t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

# 0부터 5미만까지 1씩 증가하는 데이터로 이루어진 텐서 생성
t6 = torch.arange(5)
print(t6)

tensor([[19, 13]])
tensor([[0.6698, 0.5281, 0.7939]])
tensor([[ 0.1970, -0.5411, -0.2311]])
tensor([[10.4176, 10.6531],
        [11.2185,  9.6710],
        [ 9.8560, 10.0624]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])


In [10]:
# 시드를 고정하여 동일한 난수 생성
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

# 시드를 똑같이 설정하면 동일한 랜덤 텐서 생성
torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)


tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


---
**🔎기술적 사항/고찰 내용**

**torch.randint()**

- 주어진 범위 [low, high) 내의 정수로 구성된 텐서를 생성한다.

**torch.rand():**

- 0과 1 사이의 실수로 구성된 텐서를 생성한다.

**torch.randn():**

- 평균이 0, 표준편차가 1인 정규분포에서 값을 추출하여 텐서를 생성한다.

**torch.normal():**

- 지정된 평균과 표준편차를 가지는 정규분포에서 값을 추출하여 텐서를 생성한다.

**torch.linspace():**

- 시작점과 끝점 사이를 steps 개수로 균등하게 나눈 값을 포함하는 텐서를 생성한다.

**torch.arange()**:

- 0부터 시작하여 지정된 끝까지의 값을 1씩 증가시키며 나열한 텐서를 생성한다.

**torch.manual_seed()**:

- 난수 생성기의 시드를 고정하여 동일한 난수를 재현할 수 있게 한다. 한 번 설정된 시드는 이후의 모든 무작위 값이 동일하게 나오도록 보장한다.
- 동일한 시드를 설정하면 항상 같은 결과를 얻을 수 있어 디버깅이나 실험을 반복할 때 유용하다.

<br/><br/>
## **e_tensor_type_conversion**

In [11]:
a = torch.ones((2, 3))
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16)
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

d = b.to(torch.int32) # int16 타입의 텐서 b를 int32 타입으로 변환
print(d)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [12]:
double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

double_d = torch.zeros(10, 2).double() # double 타입으로 변환
short_e = torch.ones(10, 2).short() # short 타입으로 변환

double_d = torch.zeros(10, 2).to(torch.double) # double 타입으로 변환
short_e = torch.ones(10, 2).to(dtype=torch.short) # short 타입으로 변환

double_d = torch.zeros(10, 2).type(torch.double) # double 타입으로 변환
short_e = torch.ones(10, 2). type(dtype=torch.short) # short 타입으로 변환

print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16


In [13]:
double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype) # double_f와 short_g를 곱한 텐서의 데이터 타입 출력

torch.float64


---
**🔎기술적 사항/고찰 내용**

타입을 변환하는 방법

- **.double()**
- **.to(** torch.double **)**
- **.type(** torch.double **)**

연산 후 결과 데이터 타입

- 텐서 간의 연산 후 데이터 타입은 더 높은 정밀도의 타입이 유지된다.

<br/><br/>
## **f_tensor_operations**

In [14]:
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
# 덧셈 연산
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [15]:
# 뺄셈 연산
t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [16]:
# 곱셈 연산
t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [17]:
# 나눗셈 연산
t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


---
**🔎기술적 사항/고찰 내용**

텐서 간의 연산 함수 종류 

- **torch.add()**: 두 텐서의 각 요소를 더한다.
- **torch.sub()**: 두 텐서의 각 요소를 뺀다.
- **torch.mul()**: 두 텐서의 각 요소를 곱한다.
- **torch.div()**: 두 텐서의 각 요소를 나눈다.

<br/><br/>
## **g_tensor_operations_mm**

In [18]:
# torch.dot(): 1차원 벡터 간의 내적 계산
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())
# 2*2 + 3*1 = 7

tensor(7) torch.Size([])


In [19]:
# torch.mm(): 2차원 행렬 간의 행렬 곱 계산
t2 = torch.randn(2, 3) # (2, 3)
t3 = torch.randn(3, 2) # (3, 2)
t4 = torch.mm(t2, t3) # (2, 2)
print(t4, t4.size())

tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])


In [20]:
# torch.bmm(): 3차원 배치 행렬 간의 곱 계산
t5 = torch.randn(10, 3, 4) # (10, 3, 4)
t6 = torch.randn(10, 4, 5) # (10, 4, 5)
t7 = torch.bmm(t5, t6) # (10, 3, 5)
print(t7.size())

torch.Size([10, 3, 5])


---
**🔎기술적 사항/고찰 내용**

텐서 간의 연산 함수

- **torch.dot()**
    - 1차원 벡터 간의 내적을 계산한다.
    - 결과: 스칼라 값이 반환된다.

- **torch.mm()**
    - 2차원 텐서 간의 행렬 곱을 계산한다.
    - 두 행렬의 행과 열 크기에 따라 행렬이 반한된다.
    - ex. (2, 3)과 (3, 2) -> (2, 2)

- **torch.bmm()**
    - 3차원 배치 행렬 간의 곱을 계산한다.
    - 배치 크기와 행렬 곱의 규칙에 따라 행렬이 반환된다.

<br/><br/>
## **h_tensor_operations_matmul**

In [21]:
# vector x vector: dot product
t1 = torch.randn(3) # 1차원
t2 = torch.randn(3) # 1차원
print(torch.matmul(t1, t2).size()) # 내적 계산

torch.Size([])


In [22]:
# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4) # 2차원
t4 = torch.randn(4) # 1차원
print(torch.matmul(t3, t4).size()) # 내적 계산

torch.Size([3])


In [23]:
# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4) # 3차원
t6 = torch.randn(4) # 1차원
print(torch.matmul(t5, t6).size()) # 내적 계산

torch.Size([10, 3])


In [24]:
# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4) # 3차원
t8 = torch.randn(10, 4, 5) # 3차원
print(torch.matmul(t7, t8).size()) # 내적 계산

torch.Size([10, 3, 5])


In [25]:
# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4) # 3차원
t10 = torch.randn(4, 5) # 2차원
print(torch.matmul(t9, t10).size())  # 내적 계산

torch.Size([10, 3, 5])


---
**🔎기술적 사항/고찰 내용**

**torch.matmal()** 을 사용하여 다양한 차원의 텐서끼리 곱셈을 할 수 있다.

- 벡터 x 벡터: 1차원 벡터 간의 내적을 계산한다.
- 행렬 x 벡터: 행렬과 벡터 간의 곱을 계산한다.
- 배치된 행렬 x 벡터: 각 배치된 행렬에 벡터를 곱한다.
- 배치된 행렬 x 배치된 행렬: 각 배치에 대해 행렬 곱을 계산한다.
- 배치된 행렬 x 일반 행렬: 배치된 행렬에 일반 행렬을 곱한다.

<br/><br/>
## **i_tensor_broadcasting**

In [26]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2) # t1의 각 요소에 t2 스칼라 곱한 값 출력하기
# [1.0 * 2.0, 2.0 * 2.0, 3.0 * 2.0]

t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4) # t3의 각 행에 t4를 브로드캐스팅하여 빼기

tensor([2., 4., 6.])
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


In [27]:
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)
print(t5 - 2.0)
print(t5 * 2.0)
print(t5 / 2.0)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [28]:
def normalize(x):
  return x / 255

t6 = torch.randn(3, 28, 28) # (3, 28, 28)
print(normalize(t6).size()) # t6의 각 요소를 255로 나누어 정규화한 값 출력하기

torch.Size([3, 28, 28])


In [29]:
# 서로 다른 크기의 텐서에 브로드캐스팅으로 덧셈하기
t7 = torch.tensor([[1, 2], [0, 3]]) 
t8 = torch.tensor([[3, 1]]) 
t9 = torch.tensor([[5], [2]]) 
t10 = torch.tensor([7]) 
print(t7 + t8) 
print(t7 + t9) 
print(t8 + t9) 
print(t7 + t10) 

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [30]:
# 브로드캐스팅은 같지 않은 차원을 자동으로 맞추어 계산함
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)
print(t12.shape)


t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)
print(t14.shape)
# t14의 세 번째 차원이 2로 확장된다. 1->2
# (4, 3, 2)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)
print(t16.shape)
# t16의 첫 번째 차원이 3으로 확장된다. 1->3
# (4, 3, 2)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)
print((t17 + t18).size())
# t18의 두 번째 차원이 4로 확장된다. 1->4
# (5, 3, 4, 1)

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())
# t19의 첫 번째 차원이 3으로 확장된다. 1->3
# (5, 3, 4, 1)

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())
# t21의 모든 차원이 확장되어 t22와 동일한 크기가 된다.
# (3, 1, 7)

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())
# t24의 두 번째 차원이 3으로 확장된다. 1->3

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

# 브로드캐스팅의 규칙
# -> 텐서의 각 차원은 같거나 한 차원이 1이어야 한다.
# 하지만 t25의 2와 t26의 3은 같지 않으며 어느것도 1이 아니다.
# 따라서 이 부분에서 충돌이 생긴다.
# 만약 t26이 (1, 1, 1)이라면 충돌이 생기지 않을 것이다.


torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])


In [31]:
t27 = torch.ones(4) * 5 # 각 요소에 5 곱하기 
print(t27)

t28 = torch.pow(t27, 2) # t27의 각 요소에 제곱 계산
print(t28)

exp = torch.arange(1., 5.) # [ 1.,  2.,  3.,  4.]
a = torch.arange(1., 5.) # [ 1.,  2.,  3.,  4.]
t29 = torch.pow(a, exp) # a의 각 요소에 exp의 요소를 제곱하여 계산
print(t29)
# [1^1, 2^2, 3^3, 4^4]

tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


---
**🔎기술적 사항/고찰 내용**

**브로드캐스팅**

- PyTorch에서 브로드캐스팅을 자동으로 텐서의 차원을 맞추어서 연산을 할 수 있게 한다.
- 뒤에서부터 차원을 맞추어 본다.
- 텐서의 각 차원은 같거나 하나가 1이어야 한다.
- 만약 하나가 1이면 해당 차원이 다른 텐서의 크기로 확장된다.

**지수 연산**

- **torch.pow()** 으로 텐서의 각 요소에 지수 연산을 할 수 있다.

<br/><br/>
## **j_tensor_indexing_slicing**

In [32]:
x = torch.tensor(
  [[0, 1, 2, 3, 4], # 0번째 행
   [5, 6, 7, 8, 9], # 1번째 행
   [10, 11, 12, 13, 14]] # 2번째 행
)

print(x[1]) # 1번째 행
print(x[:, 1]) # 각 행의 1번째 열
print(x[1, 2]) # 1번째 행, 2번째 열
print(x[:, -1]) # 각 행의 마지막 열
print(x[1:]) # 1번째부터 마지막 행
print(x[1:, 3:]) # 1번째부터 마지막 행, 3번째부터 마지막 열

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


In [33]:
y = torch.zeros((6, 6))
y[1:4, 2] = 1 # 1번째부터 4번째 행의 2번째 열을 1로 설정
print(y)
print(y[1:4, 1:4])

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [34]:
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


---
**🔎기술적 사항/고찰 내용**

슬라이싱

-  텐서의 특정 부분을 쉽게 선택하고 수정할 수 있게 해준다.

<br/><br/>
## **k_tensor_reshaping**

In [35]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2) # 텐서의 모양을 (3, 2)로 바꾸기
t3 = t1.reshape(1, 6) # 텐서의 모양을 (1, 6)로 바꾸기
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)  # 텐서의 모양을 (2, 4)로 바꾸기
t5 = torch.arange(6).view(2, 3)  # 텐서의 모양을 (2, 3)로 바꾸기
print(t4)
print(t5)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [36]:
t6 = torch.tensor([[[1], [2], [3]]]) # ()

t7 = t6.squeeze() # 크기가 1인 차원 제거
# 
t8 = t6.squeeze(0) # 첫 번째 차원 제거
# 
print(t7)
print(t8)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


In [37]:
t9 = torch.tensor([1, 2, 3])

t10 = t9.unsqueeze(1) # 첫 번째 위치에 새로운 차원 추가하기
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1) # 첫 번째 위치에 새로운 차원 추가하기
print(t12, t12.shape)

tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


In [38]:
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t14 = t13.flatten()  # 모든 차원을 평탄화하기 (6,)
print(t14)

t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15) # 모든 차원을 평탄화하기
t17 = torch.flatten(t15, start_dim=1) # 첫 번째 차원부터 평탄화하기
print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [39]:
t18 = torch.randn(2, 3, 5)
print(t18.shape)
print(torch.permute(t18, (2, 0, 1)).size()) # 차원을 (2, 0, 1) 순서로 재배치하기

t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

t20 = torch.permute(t19, dims=(0, 1))  # 모양 유지하기
t21 = torch.permute(t19, dims=(1, 0))  # 차원 전치하기
print(t20)
print(t21)

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [40]:
t22 = torch.transpose(t19, 0, 1) # 차원 전치하기
print(t22)
t23 = torch.t(t19) # 2차원 행렬 전치하기
print(t23)

tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


---
**🔎기술적 사항/고찰 내용**

텐서의 모양을 변경하는 연산

-  **view()**: 텐서의 모양을 바꾼다. (메모리 레이아웃이 그대로다.)
-  **reshape()**: 텐서릐 모양을 바꾼다. (메모리를 새로 할당할 수 있다.)

-  **squeeze()**: 차원을 제거한다.
-  **unsqueeze()**: 차원을 추가한다.
  
-  **flatten()**: 차원을 평탄화한다.
-  **permute()**: 차원을 재배치한다.
-  **transpose()**, **t()**: 텐서를 전치한다.

<br/><br/>
## **l_tensor_concat**

In [41]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

# 3차원 텐서간의 결합
t4 = torch.cat([t1, t2, t3], dim=1) # (2, 1+3+2, 3)
print(t4.shape)

torch.Size([2, 6, 3])


In [42]:
t5 = torch.arange(0, 3)  # [0, 1, 2]
t6 = torch.arange(3, 8)  # [3, 4, 5, 6, 7]

# 1차원 텐서 간의 결합
t7 = torch.cat((t5, t6), dim=0) # 첫 번째 차원에서 이어붙이기
# [0, 1, 2, 3, 4, 5, 6, 7]

print(t7.shape)
print(t7)

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [43]:
t8 = torch.arange(0, 6).reshape(2, 3) # (2, 3)
t9 = torch.arange(6, 12).reshape(2, 3) # (2, 3)

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0) # 첫 번째 차원에서 결합하기 (2+2, 3)
print(t10.size())
print(t10)

t11 = torch.cat((t8, t9), dim=1) # 두 번째 행에서 결합하기 (2, 3+3)
print(t11.size())
print(t11)

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [44]:
t12 = torch.arange(0, 6).reshape(2, 3) # (2, 3)
t13 = torch.arange(6, 12).reshape(2, 3) # (2, 3)
t14 = torch.arange(12, 18).reshape(2, 3) # (2, 3)


t15 = torch.cat((t12, t13, t14), dim=0) # 첫 번째 차원에서 결합하기 (2+2+2, 3)
print(t15.size()) 
print(t15)

t16 = torch.cat((t12, t13, t14), dim=1) # 두 번째 차원에서 결합하기 (2, 3+3+3)
print(t16.size())
print(t16)

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [45]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # (1, 2, 3)
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # (1, 2, 3)

# 3차원 텐서 간의 결합
t19 = torch.cat((t17, t18), dim=0) # (1+1, 2, 3)
print(t19.size())
print(t19)

t20 = torch.cat((t17, t18), dim=1) # (1, 2+2, 3)
print(t20.size())
print(t20)

t21 = torch.cat((t17, t18), dim=2) # (1, 2, 3+3)
print(t21.size())
print(t21)

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


---
**🔎기술적 사항/고찰 내용**

텐서를 결합하는 방식

- **torch.cat()**
  
     - 지정된 차원에서 텐서를 결합한다.
     - 결합하려는 차원을 제외한 다른 차원의 크기는 동일해야 한다.
     - dim=0: 첫 번째 차원, dim=1: 두 번째 차원, dim=2: 세 번째 차원

<br/><br/>
## **m_tensor_stacking**

In [46]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0) # 첫 번째 차원을 따라 텐서 쌓기
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0) # 각 텐서에 첫 번째 차원을 추가하고 결합하기
print(t3.shape, t3.equal(t4)) # 두 결과가 같은지 확인하기

t5 = torch.stack([t1, t2], dim=1) # 두 번째 차원을 따라 텐서 쌓기
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1) # 각 텐서에 두 번째 차원을 추가하고 결합하기
print(t5.shape, t5.equal(t6)) # 두 결과가 같은지 확인하기

t7 = torch.stack([t1, t2], dim=2) # 세 번째 차원을 따라 텐서 쌓기
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2) # 각 텐서에 세 번째 차원을 추가하고 결합하기
print(t7.shape, t7.equal(t8)) # 두 결과가 같은지 확인하기

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True


In [47]:
t9 = torch.arange(0, 3) # [0, 1, 2]
t10 = torch.arange(3, 6) # [3, 4, 5]
print(t9.size(), t10.size()) # 각각의 크기: 3

t11 = torch.stack((t9, t10), dim=0) # 첫 번째 차원을 따라 벡터 쌓기 (2, 3)
print(t11.size())
print(t11)
# [[0, 1, 2],
# [3, 4, 5]]

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0) # 각 벡터에 첫 번째 차원을 추가하고 결합하기
print(t11.equal(t12))
# [[0, 1, 2],
# [3, 4, 5]]

t13 = torch.stack((t9, t10), dim=1)  # 두 번째 차원을 따라 벡터 쌓기 (3, 2)
print(t13.size())
# [[0, 3],
# [1, 4],
# [2, 5]]

t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1) # 각 벡터에 두 번째 차원을 추가하고 결합하기
print(t13.equal(t14))
# [[0, 3],
# [1, 4],
# [2, 5]]

torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
True


---
**🔎기술적 사항/고찰 내용**

텐서를 결합하는 방식

- **torch.stack()**
    - 지정한 차원을 기준으로 새로운 차원을 추가하면서 텐서를 쌓는다.

- **torch.cat()**
     - 기존의 차원에서 텐서를 결합한다.
     - unsqeeze()를 사용해서 차원을 추가할 수 있다.

<br/><br/>
## **n_tensor_vstack_hstack**

In [48]:
# 수직 스택
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2)) # 두 벡터를 수직으로 쌓기
print(t3)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [49]:
t4 = torch.tensor([[1], [2], [3]]) # (3, 1)
t5 = torch.tensor([[4], [5], [6]]) # (3, 1)
t6 = torch.vstack((t4, t5)) # 두 벡터를 수직으로 쌓기 (3+3, 1)
print(t6.shape) 

torch.Size([6, 1])


In [50]:
t7 = torch.tensor([ # (2, 2, 3)
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)

t8 = torch.tensor([ # (2, 2, 3)
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)

t9 = torch.vstack([t7, t8]) # (4, 2, 3)
print(t9.shape) 
print(t9)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


In [51]:
# 수평 스택
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11)) # 두 벡터를 수평으로 결합하기
print(t12)

tensor([1, 2, 3, 4, 5, 6])


In [52]:
t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14)) # 두 벡터를 수평으로 결합하기
print(t15)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [53]:
t16 = torch.tensor([ # (2, 2, 3)
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)

t17 = torch.tensor([ # (2, 2, 3)
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)

t18 = torch.hstack([t16, t17]) # 두 벡터를 수평으로 결합하기 (2, 4, 3)
print(t18.shape)  
print(t18)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


---
**🔎기술적 사항/고찰 내용**

수직 스택

- **torch.vstack()**
  
  - 지정된 두 벡터를 첫 번째 차원을 기준으로 수직으로 결합한다.
  - 행을 추가하는 방식이다.

수평 스택

- **torch.hstack()**
  
  - 지정된 두 벡터를 두 번째 차원을 기준으로 수평으로 결합한다.
  - 열을 추가하는 방식이다.

<br/><br/>

## **📌숙제 후기**

hw1-1
---

처음에는 딥러닝에 대한 이론 수업을 들었지만 개념들이 워낙 방대하고 생소해서 그리 쉽게 와닿지는 않았다.
하지만 이번 첫 번째 과제를 통해 직접 코드를 작성하고 실행해보면서 이론으로만 알고 있던 개념들이 조금씩 구체적으로 다가왔다. 
이번 과제는 생각했던 것보다 분량이 꽤 많아서 시간을 꽤 많이 투자해야 했다. 그럼에도 불구하고 내용 자체는 복잡하지 않았기 때문에 a부터 n까지 하나하나 단계를 완성해 나가면서 큰 어려움 없이 진행할 수 있었다. 특히 문제를 해결할 때마다 단계별로 성과가 보이는 것이 굉장히 뿌듯했고, 이를 통해 딥러닝의 기초적인 개념들을 자연스럽게 익혀나갈 수 있었다. 과제의 분량이 많았던 만큼 시간 관리가 부족했던 점도 아쉬웠다. 다음에는 좀 더 계획적으로 시간을 관리해서 여유 있게 공부하고 싶다.